spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/kdx
    username: myuser
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

