DROP TABLE IF EXISTS expense;
DROP TABLE IF EXISTS member_settlement;
DROP TABLE IF EXISTS member;
DROP TABLE IF EXISTS settlement;

CREATE TABLE member
(
    id       bigint generated by default as identity,
    name     varchar(255),
    password varchar(255),
    nickname varchar(255),
    primary key (id)
);

CREATE TABLE settlement
(
    id   bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

CREATE TABLE member_settlement
(
    id            bigint generated by default as identity,
    member_id     bigint,
    settlement_id bigint,
    primary key (id),
    foreign key (member_id) REFERENCES member,
    foreign key (settlement_id) REFERENCES settlement
);

CREATE TABLE expense
(
    id bigint generated by default as identity,
    name varchar(255),
    member_id bigint,
    settlement_id bigint,
    amount decimal,
    created_at timestamp default CURRENT_TIMESTAMP(),
    primary key(id),
    foreign key (member_id) REFERENCES member,
    foreign key (settlement_id) REFERENCES settlement
);

INSERT INTO member(name, password, nickname) VALUES ('foo', 'bar', 'baz');
INSERT INTO settlement(name) VALUES ('foo');
INSERT INTO member_settlement(member_id, settlement_id) VALUES (1, 1);
INSERT INTO expense(name, member_id, settlement_id, amount) VALUES ('foo', 1, 1, 100);